phoenix:
  image: birdhouse/pyramid-phoenix
  command: make update update-user start
  volumes:
    - .docker.cfg:/opt/birdhouse/custom.cfg
  ports:
    - "9001:9001"
    - "8081:8081"
    - "8443:8443"
  links:
    - mongodb
    - redis
    - pycsw
mongodb:
  image: birdhouse/mongodb
redis:
  image: birdhouse/redis
pycsw:
  image: birdhouse/pycsw
  command: make update-config start
  environment:
    - HOSTNAME=pycsw
ncwms2:
  image: birdhouse/ncwms2
  ports:
    - "8080:8080"
solr:
  image: birdhouse/solr
  ports:
    - "8983:8983"
malleefowl:
  image: birdhouse/malleefowl
  command: make update-config update-user start
  ports:
    - "48091:9001"
    - "38091:38091"
    - "28091:28091"
    - "8091:8091"
  environment:
    - HOSTNAME=adelie.d.dkrz.de
  volumes:
    - data:/data
  volume_driver: local
 
