phoenix:
  image: birdhouse/pyramid-phoenix
  ports:
    - "9001:9001"
    - "8081:8081"
    - "8443:8443"
  environment:
    - HOSTNAME
  volumes_from:
    - mongodb
  links:
    - mongodb
    - redis
    - pycsw
mongodb:
  image: birdhouse/mongodb
  command: make update-config update-user start
  volumes:
    - data:/data
  volume_driver: local
redis:
  image: birdhouse/redis
  command: make update-config update-user start
  volumes_from:
    - mongodb
pycsw:
  image: birdhouse/pycsw
  command: make update-config update-user start
  environment:
    - HOSTNAME=pycsw
  extra_hosts:
    - "pycsw:127.0.0.1" 
  volumes_from:
    - mongodb
malleefowl:
  image: birdhouse/malleefowl
  command: make update-config update-user start
  ports:
    - "48091:9001"
    - "38091:38091"
    - "28091:28091"
    - "8091:8091"
  environment:
    - HOSTNAME
  volumes_from:
    - mongodb
ncwms2:
  image: birdhouse/ncwms2
  ports:
    - "48080:9001"
    - "8080:8080"
  volumes_from:
    - mongodb
solr:
  image: birdhouse/solr
  ports:
    - "48983:9001"
    - "8983:8983"
  volumes_from:
    - mongodb

