phoenix:
  image: birdhouse/pyramid-phoenix
  command: make start
  ports:
    - "8081:8081"
    - "8443:8443"
  links:
    - mongodb
    - redis
    - pycsw
    - ncwms2
    - solr
    - malleefowl
mongodb:
  image: birdhouse/mongodb
  command: make start
redis:
  image: birdhouse/redis
  command: make start
pycsw:
  image: birdhouse/pycsw
  command: make start
ncwms2:
  image: birdhouse/ncwms2
  command: make start
solr:
  image: birdhouse/solr
  command: make start
malleefowl:
  image: birdhouse/malleefowl
  command: make update-config start
  environment:
    HOSTNAME: malleefowl

