name: pyramid-phoenix 
channels:
  - defaults
  - birdhouse
dependencies:
  - python=2.7.12 
  - setuptools=23.0.0
  - curl=7.49.0 
  - pyopenssl=0.15.1 
  - cryptography=1.0.2
# tests
  - pytest 
  - pytest-pep8 
# ipython
  - ipython
# sphinx
  - sphinx 
  - sphinx_rtd_theme
# phoenix
  - nginx=1.10.1
  - supervisor=3.1.3
  - gunicorn=19.1.0
  - gevent=1.1.1
  - lxml=3.6.0
  - mako=1.0.4 
  - dateutil=2.4.1 
  - requests=2.10.0 
  - pyyaml=3.11
  - pygments=2.1.3 
  - pytz=2016.4
  - owslib=0.11.2
# celery
  - celery=3.1.19
  - kombu=3.0.32
# mongodb
  - pymongo=3
  - mongodb=2.4.6
# twitcher
  - pywps=3.2.6
# phoenix extensions 
  - python-swiftclient=2.4.0
  - threddsclient=0.3.4       
  - python-ldap=2.4.13
  - funcsigs=1.0.2
  - bird-feeder=0.2.0
  - pip:
      - genshi==0.7
